version: 2

build:
  image: latest

formats: all

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
